"use client";

import { useEffect, useState } from "react";
import { api, AuthGate, Button, Shell, Status, Busy } from "./admin-ui";

export function AdminAccess({ publicId }: { publicId: string }) {
  const [url, setUrl] = useState(""); const [error, setError] = useState(""); const [copied, setCopied] = useState(false); const [printing, setPrinting] = useState(false);
  useEffect(() => { api<{ public_url: string }>(`/api/admin/events/${publicId}/access`).then(x => setUrl(x.public_url)).catch(e => setError(e.message)); }, [publicId]);
  async function copy() { try { await navigator.clipboard.writeText(url); setCopied(true); } catch { setError("COPY_FAILED"); } }
  function print() { setPrinting(true); window.print(); window.setTimeout(() => setPrinting(false), 500); }
  return <AuthGate><Shell><div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-primary">Share access</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-tight">Put the doorway on the table.</h1><p className="mt-3 text-muted-foreground">Guests can scan this access card or open the public link.</p></div><Button secondary onClick={() => window.history.back()}>Back to event</Button></div>{error ? <Status error message={error === "OFFLINE" ? "Access details are unavailable offline." : "This access card is unavailable."} action={<Button secondary onClick={() => window.location.reload()}>Retry</Button>} /> : !url ? <div className="mt-8"><Busy label="Loading access details" /></div> : <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_18rem]"><section className="rounded-[10px] border border-border bg-card p-6 shadow-[var(--shadow-1)]"><h2 className="text-xl font-semibold">Public URL</h2><label className="mt-4 block text-sm font-semibold" htmlFor="public-url">Share link<input id="public-url" readOnly value={url} className="mt-2 h-11 w-full rounded-md border bg-muted px-3 text-sm" /></label><div className="mt-4 flex flex-wrap gap-2"><Button onClick={copy}>{copied ? "Copied" : "Copy link"}</Button><Button secondary disabled={printing} onClick={print}>{printing ? "Opening print dialog…" : "Print access card"}</Button></div>{copied && <Status message="Link copied to your clipboard." />}</section><section className="rounded-[10px] border border-border bg-card p-6 text-center shadow-[var(--shadow-1)]"><h2 className="text-xl font-semibold">QR access</h2><div aria-label="QR visual placeholder" className="mx-auto mt-5 grid aspect-square max-w-52 grid-cols-9 gap-1 rounded-md border-8 border-foreground bg-card p-2">{Array.from({ length: 81 }, (_, i) => <i key={i} className={(i * 17 + publicId.charCodeAt(i % publicId.length)) % 5 < 2 ? "bg-foreground" : "bg-transparent"} />)}</div><p className="mt-4 text-xs text-muted-foreground">Bounded visual for print planning. Use the public link if scanning is unavailable.</p></section></div>}</div></Shell></AuthGate>;
}
